### ISSUE TITLE
Corrigir link para a página do campus

### ISSUE THREAD

**Issue by manoelangelo** [ifpb/secif#4]
Na verdade, a fanpage do Campus é:
https://www.facebook.com/ifpbcampusjpoficial/

**Comment by ajunior** [comment]
A ideia é colocar as redes sociais da própria SECIF. Mas não tem ainda, é preciso criá-las. Veremos com o Prof Marcílio numa próxima reunião. Por enquanto podemos deixar redes sociais do campus.
